# Pre-commit hooks configuration
# Install with: pre-commit install

repos:
  - repo: local
    hooks:
      - id: sync-requirements
        name: Sync requirements.txt from pyproject.toml
        entry: bash -c 'if [ -f pyproject.toml ]; then make export-requirements; fi'
        language: system
        files: pyproject.toml
        pass_filenames: false
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files